apiVersion: v1
kind: Service
metadata:
  name: hello-app-svc
  namespace: hello-app
spec:
  type: NodePort
  selector:
    app: hello-app
  ports:
    - protocol: TCP
      port: 8080    # 서비스 자체(ClusterIP)가 노출할 포트 (클러스터 내부용)
      targetPort: 8080  # 서비스가 트래픽을 전달할 Pod 내부의 컨테이너 포트
